name: lost_item_finder_iot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:

    sdk: flutter
  wifi_scan : ^0.4.0
  permission_handler : ^11.0.1
  http : ^1.3.0
  vibration : ^3.1.3
  logger : ^1.0.0
  wifi_iot : ^0.3.19+2
    
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/animations/bluetooth.json
    -  assets/animations/loading.json
    
     

          
